//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mainMasterpiesce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotAvailableTime
    {
        public int notavailableId { get; set; }
        public Nullable<int> doctorId { get; set; }
        public string timenotavailble { get; set; }
    
        public virtual doctor doctor { get; set; }
    }
}
